### ISSUE TITLE
可否增加 cache 过期配置

### ISSUE THREAD

**Issue by edenleung** [php-casbin/think-authz#18]
发现代码有数据库查询缓存，并且还是永久的，能否可以提供过期选项。

还是需要开发者 手动清缓存？

**Comment by leeqvip** [comment]
缓存使用官方框架内置，参考THINKPHP文档：[数据库缓存](https://www.kancloud.cn/manual/thinkphp6_0/1037553)，[杂项-缓存](https://www.kancloud.cn/manual/thinkphp6_0/1037634)，可以在缓存配置中设置`expire`。

**Comment by leeqvip** [comment]
by #47
