### ISSUE TITLE
API接口 ---Enforcer::addPermissionForUser('writer', 'articles','edit');   文档参数有与代码中facde参数不符

### ISSUE THREAD

**Issue by jhz-code** [php-casbin/think-authz#19]
差了一个action 参数  

 包中的代码:
 * @method mixed addPermissionForUser(string $username,string $policy) static 为用户或角色添加权限

文档中API 调用：

赋予权限给某个用户或角色：
// to user
Enforcer::addPermissionForUser('eve', 'articles', 'read');
// to role
Enforcer::addPermissionForUser('writer', 'articles','edit');

**Comment by jhz-code** [comment]
* @method mixed hasPermissionForUser(string $username,string $policy) static 确定用户是否具有权限

好几个参数都对不上

**Comment by hsluoyz** [comment]
@basakest

**Comment by jhz-code** [comment]
这些方法中 在实际函数中都缺了一个参数
  // adds permissions to a user
        Enforcer::addPermissionForUser('eve', 'articles', 'read');
        Enforcer::deletePermission('articles', 'read'); // returns false if the permission does not exist (aka not affected).
        Enforcer::deletePermissionForUser('eve', 'articles', 'read');
        Enforcer::hasPermissionForUser('eve', 'articles', 'read');  // true or false

**Comment by hsluoyz** [comment]
@techoner
