### ISSUE TITLE
Could not find a version of package casbin/think-authz

### ISSUE THREAD

**Issue by wfz90** [php-casbin/think-authz#2]
请问这个怎么办 Could not find a version of package casbin/think-authz matching your minimum-stabilit
  y (stable). Require it with an explicit version constraint allowing its desired stabi
  lity.

**Comment by hsluoyz** [comment]
@techoner

**Comment by leeqvip** [comment]
由于tp6尚未发布稳定版，所以think-authz也未发布稳定版，尝鲜可以安装开发版：
```
 composer require casbin/think-authz:dev-master
```

**Comment by unrealsmart** [comment]
有点慢，加上-vvv，或者去喝会茶

**Comment by leeqvip** [comment]
使用阿里镜像
```
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
```
