### ISSUE TITLE
@method mixed getPermissionsForUser(string $username) static 获取用户的权限返回空

### ISSUE THREAD

**Issue by jhz-code** [php-casbin/think-authz#20]
@method mixed getPermissionsForUser(string $username) static 

获取角色权限可以正常获取

获取某个用户的权限返回为空

**Comment by hsluoyz** [comment]
@basakest 

/cc @techoner

**Comment by leeqvip** [comment]
@jhz-code `getPermissionsForUser`只能获取直接权限，使用[getImplicitPermissionsForUser](https://github.com/php-casbin/php-casbin/blob/master/src/Enforcer.php#L275)获取间接权限。

**Comment by jhz-code** [comment]
@techoner  明白 感谢
