### ISSUE TITLE
有实际的应用项目吗？

### ISSUE THREAD

**Issue by km3945** [php-casbin/think-authz#22]
有实际的应用项目吗？
想参考下。

**Comment by hsluoyz** [comment]
@basakest 

/cc @techoner

**Comment by leeqvip** [comment]
@km3945 See https://github.com/php-casbin/think-authz/network/dependents?package_id=UGFja2FnZS02NjQ3MDE5OTY%3D

**Comment by JeasonLaung** [comment]
建议大家玩玩就算了，别用。数据库根本不能维护，你们可以看看，看懂了我叫你大哥
![image](https://user-images.githubusercontent.com/44773434/147555093-4fb2ec2e-39f0-438b-9795-746af15188a8.png)

**Comment by hsluoyz** [comment]
@JeasonLaung https://casbin.org/docs/zh-CN/policy-storage#database-storage-format
