### ISSUE TITLE
怎么添加自定义函数？

### ISSUE THREAD

**Issue by raymondZhong** [php-casbin/think-authz#23]
怎么添加自定义函数？

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by leeqvip** [comment]
![image](https://user-images.githubusercontent.com/35752209/125194646-d14d5a00-e284-11eb-9ae5-1792b7b21525.png)
@raymondZhong

**Comment by raymondZhong** [comment]
这样的话 就是原生的 Enforcer  还用这个扩展有什么用呢？

**Comment by raymondZhong** [comment]
这样的话 就是原生的 Enforcer 还用这个扩展有什么用呢？
@techoner

**Comment by chnljx** [comment]
这个扩展是搭配thinkphp6使用，当然用原生的很多方法就需要自己去实现

**Comment by leeqvip** [comment]
参考：https://casbin.org/docs/en/function
