### ISSUE TITLE
grouping policy elements do not meet role definition

### ISSUE THREAD

**Issue by Bigweixi** [php-casbin/think-authz#24]
我卸载了一次  再次安装不知道为什么一直出现
grouping policy elements do not meet role definition   这个错误   流程都是正确的

**Comment by hsluoyz** [comment]
@basakest @techoner

**Comment by leeqvip** [comment]
@pengRW Can you provide an example ?

**Comment by Bigweixi** [comment]
@techoner  我记得我之前就是  在composer.json 里面删除了他  然后 使用composer update 安装 就出现了 这个错误  , 使用原生的composer casbin 扩展是能运行的

**Comment by leeqvip** [comment]
@pengRW 如果是安装过，需要更新，就不要执行`php think tauthz:publish`，这将覆盖config/tauthz-rbac-model.conf 和 config/tauthz.php 文件.
