### ISSUE TITLE
TP 6.0 安装问题

### ISSUE THREAD

**Issue by mfkps** [php-casbin/think-authz#3]
使用composer安装出现以下错误：

  [InvalidArgumentException]
  Could not find a version of package casbin/think-authz matching your minimum-stability (stable). Require it with an
   explicit version constraint allowing its desired stability.

**Comment by leeqvip** [comment]
@mfkps
由于tp6尚未发布稳定版，所以think-authz也未发布稳定版，尝鲜可以安装开发版：
```
composer require casbin/think-authz:dev-master
```
Duplicate of #2

**Comment by mfkps** [comment]
开发版
composer require casbin/think-authz:dev-master
安装正常，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Foufou"<notifications@github.com&gt;; 
发送时间: 2019年10月19日(星期六) 中午11:23
收件人: "php-casbin/think-authz"<think-authz@noreply.github.com&gt;; 
抄送: "Mfkps"<mfkpsz@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [php-casbin/think-authz] TP 6.0 安装问题 (#3)




由于tp6尚未发布稳定版，所以think-authz也未发布稳定版，尝鲜可以安装开发版：
 composer require casbin/think-authz:dev-master  
Duplicate of #2

**Comment by yzh52521** [comment]
安装了这个扩展 影响了 本地上传的 \think\Facade\Filesystem::getDiskConfig ('public', 'url') 这个方法

**Comment by techoner** [comment]
麻烦在issues里回复------------------ 原始邮件 ------------------
发件人: "听风吹雨"<notifications@github.com>
发送时间: 2019年10月22日(星期二) 上午9:15
收件人: "php-casbin/think-authz"<think-authz@noreply.github.com>;
抄送: "Foufou"<techlee@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [php-casbin/think-authz] TP 6.0 安装问题 (#3)



安装了这个扩展 影响了 本地上传的 \think\Facade\Filesystem::getDiskConfig ('public', 'url') 这个方法
 
&mdash;
