### ISSUE TITLE
这个缓存怎么在调试阶段关闭

### ISSUE THREAD

**Issue by Bigweixi** [php-casbin/think-authz#30]
这个缓存怎么在调试阶段关闭

**Comment by hsluoyz** [comment]
@basakest @techoner

**Comment by leeqvip** [comment]
@pengRW 缓存是自动更新，参考：https://www.kancloud.cn/manual/thinkphp6_0/1037553
目前没有配置开关。

**Comment by hsluoyz** [comment]
@basakest plz add a switch to turn off the cache

**Comment by leeqvip** [comment]
by #47
