### ISSUE TITLE
1.5.2=>1.5.3升级后的小问题

### ISSUE THREAD

**Issue by yin5th** [php-casbin/think-authz#35]
file: src/adapter/DatabaseAdapter.php
Use loadPolicyArray instead of loadPolicyLine

传递给loadPolicyArray的第一个数组参数变更了。
1.5.2 `["p", "writer","articles","edit"]`
1.5.3 `[1, "p", "writer","articles","edit"]`

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@yin5th After the upgrade, please remove the `cache` first, the query field is specified in the new version :
```php
    public function loadPolicy(Model $model): void
    {
        $rows = $this->model->cache('tauthz')->field(['ptype', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5'])->select()->toArray();
        foreach ($rows as $row) {
            $this->loadPolicyArray($this->filterRule($row), $model);
        }
    }
```
