### ISSUE TITLE
Enforcer::enforce报 “array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements”

### ISSUE THREAD

**Issue by kvfun** [php-casbin/think-authz#36]
#0 [0]ValueError in [CoreEnforcer.php line 644]

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@kvfun Please make sure that the number of parameters passed to `enforce()` is consistent with the model configuration.
