### ISSUE TITLE
感觉如果能加入restful路由权限会更好

### ISSUE THREAD

**Issue by myixyt** [php-casbin/think-authz#37]
研究了一下，好像只能一对一匹配路由权限，无法通过restful形式，请问有解决办法吗？

**Comment by leeqvip** [comment]
@myixyt  Reference: https://github.com/php-casbin/casbin-tutorials/blob/master/tutorials/RBAC-with-Casbin.md

**Comment by hsluoyz** [comment]
@myixyt see also: https://casbin.io/docs/rbac-with-pattern
