### ISSUE TITLE
ABAC怎么配置？

### ISSUE THREAD

**Issue by khongshao** [php-casbin/think-authz#38]
我把代码全翻了一遍，没有相关的代码，甚至在tauthz.php改了model也不太行

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by khongshao** [comment]
tauthz.php
`
 'abac' => [
            'model' => [
                // 可选值: "file", "text"
                'config_type' => 'file',
                'config_file_path' => config_path().'tauthz-abac-model.conf',
                'config_text' => '',
            ],

            // 适配器 .
            'adapter' => tauthz\adapter\DatabaseAdapter::class,

            /*
            * 数据库设置.a
            */
            'database' => [
                // 数据库连接名称，不填为默认配置.
                'connection' => '',
                // 策略表名（不含表前缀）
                'rules_name' => 'rules',
                // 策略表完整名称.
                'rules_table' => null,
            ],
        ],
`

tauthz-abac-model.conf   （从casbin官网复制的）
`
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner
`

**Comment by khongshao** [comment]
tauthz.php
`'abac' => [
            'model' => [
                // 可选值: "file", "text"
                'config_type' => 'file',
                'config_file_path' => config_path().'tauthz-abac-model.conf',
                'config_text' => '',
            ],

            // 适配器 .
            'adapter' => tauthz\adapter\DatabaseAdapter::class,

            /*
            * 数据库设置.a
            */
            'database' => [
                // 数据库连接名称，不填为默认配置.
                'connection' => '',
                // 策略表名（不含表前缀）
                'rules_name' => 'rules',
                // 策略表完整名称.
                'rules_table' => null,
            ],
        ]`
        
        
        tauthz-abac-model.conf（从官网下载的）
       `[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner`

**Comment by khongshao** [comment]
tauthz.php
'abac' => [
'model' => [
// 可选值: "file", "text"
'config_type' => 'file',
'config_file_path' => config_path().'tauthz-abac-model.conf',
'config_text' => '',
],

        // 适配器 .
        'adapter' => tauthz\adapter\DatabaseAdapter::class,

        /*
        * 数据库设置.a
        */
        'database' => [
            // 数据库连接名称，不填为默认配置.
            'connection' => '',
            // 策略表名（不含表前缀）
            'rules_name' => 'rules',
            // 策略表完整名称.
            'rules_table' => null,
        ],
    ]
    
    
    tauthz-abac-model.conf（从官网下载的）
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner`

**Comment by leeqvip** [comment]
@khongshao Reference: https://casbin.org/docs/en/abac
