### ISSUE TITLE
发现bug 

### ISSUE THREAD

**Issue by yuanzhihai** [php-casbin/think-authz#4]
安装了这个扩展 影响了 本地上传的 \think\Facade\Filesystem::getDiskConfig ('public', 'url') 这个方法

**Comment by leeqvip** [comment]
试了一下，并不影响
```
$res = \think\Facade\Filesystem::getDiskConfig('public', 'url');
var_dump($res); // app/controller/Index.php:12:string '/storage' (length=8)
```

贴一下你的代码及报错

**Comment by yuanzhihai** [comment]
> 试了一下，并不影响
> 
> ```
> $res = \think\Facade\Filesystem::getDiskConfig('public', 'url');
> var_dump($res); // app/controller/Index.php:12:string '/storage' (length=8)
> ```
> 
> 贴一下你的代码及报错

 $file = Request::file('image');
        try {
            validate(['image' => [
                // 限制文件大小(单位b)，这里限制为4M
                'fileSize' => 4 * 1024 * 1000,
                // 限制文件后缀，多个后缀以英文逗号分割
                'fileExt'  => 'gif,jpg,png'
            ]])->check(['image' => $file]);
            $path = 'avatar';
            $path = \think\Facade\Filesystem::disk('public')->putFile($path, $file);
            $url = \think\Facade\Filesystem::getDiskConfig('public', 'url') . DIRECTORY_SEPARATOR .$path;
            $info = [
                'path' => $path,
                'url'  => $url,
                'size' => $file->getSize(),
                'name' => $file->getFilename(),
                'mine' => $file->getMime(),
            ];
            halt($info);
        } catch (\think\exception\ValidateException $e) {
            echo $e->getMessage();
        }

以下是报错

Call to undefined method League\Flysystem\Filesystem::getDiskConfig
     * @throws BadMethodCallException
     *
     * @return mixed
     */
    public function __call($method, array $arguments)
    {
        try {
            return $this->invokePlugin($method, $arguments, $this);
        } catch (PluginNotFoundException $e) {
            throw new BadMethodCallException(
                'Call to undefined method '
                . get_class($this)
                . '::' . $method
            );
        }
    }
}

**Comment by leeqvip** [comment]
按照你的代码试了下，没有出现这个问题
你可以单独安装个新的tp项目，验证下是否存在这个问题

**Comment by yuanzhihai** [comment]
我就是新安装的 

Call to undefined method League\Flysystem\Filesystem::getDiskConfig
ThinkPHP V6.0.0RC5 { 十年磨一剑-为API开发设计的高性能框架 } - 官方手册

**Comment by leeqvip** [comment]
那你可以先将 `think-authz` 从 `composer.json` 里移除，后 `composer install`
看下有无问题

**Comment by yuanzhihai** [comment]
> 那你可以先将 `think-authz` 从 `composer.json` 里移除，后 `composer install`
> 看下有无问题
没问题啊

array:5 [▼
  "path" => "avatar/20191022/1df097f6157861645e90f91681e3498e.png"
  "url" => "/storage/avatar/20191022/1df097f6157861645e90f91681e3498e.png"
  "size" => 144069
  "name" => "phpUOAmWx"
  "mine" => "image/png"
]

**Comment by leeqvip** [comment]
那你可以`debug`下是哪里的问题吗，然后提个`PR`改进下？

**Comment by yuanzhihai** [comment]
> debug

/**
     * 获取缓存配置
     * @access public
     * @param null|string $name    名称
     * @param mixed       $default 默认值
     * @return mixed
     */
    public function getConfig(string $name = null, $default = null)
    {
        if (!is_null($name)) {
            return $this->app->config->get('filesystem.' . $name, $default);
        }

        return $this->app->config->get('filesystem');
    }

    /**
     * 获取磁盘配置
     * @param string $disk
     * @param null   $name
     * @param null   $default
     * @return array
     */
    public function getDiskConfig($disk, $name = null, $default = null)
    {
        if ($config = $this->getConfig("disks.{$disk}")) {
            return Arr::get($config, $name, $default);
        }

        throw new InvalidArgumentException("Disk [$disk] not found.");
    }

增加了这两个方法就可以了

**Comment by leeqvip** [comment]
你这是`tp`的代码吧

**Comment by yuanzhihai** [comment]
> 你这是`tp`的代码吧

在  thans\filesystem\Filesystem 类里增加的
因为你的这个扩展 覆盖了tp 的local

**Comment by yuanzhihai** [comment]
> 你这是`tp`的代码吧

你看下你的 thans\filesystem\Filesystem 这个类 和 tp的 think\Filesystem 这个类
安装你的扩展后    thans\filesystem\Filesystem 这个类里找不到 getDiskConfig 这个方法了

**Comment by leeqvip** [comment]
`think-authz` 没有使用 任何 `Filesystem` 类

**Comment by yuanzhihai** [comment]
> `think-authz` 没有使用 任何 `Filesystem` 类

哦
那估计是我的错
