### ISSUE TITLE
没支持thinkphp版本8.0，要更新下composer.json

### ISSUE THREAD

**Issue by lg970044** [php-casbin/think-authz#40]
没支持thinkphp版本8.0，要更新下composer.json

**Comment by leeqvip** [comment]
dev依赖冲突，php-coveralls 暂不支持 psr 3.0

**Comment by hsluoyz** [comment]
@leeqvip php-coveralls 这个不重要吧，只是个CI工具。以支持thinkphp 8.0等新版本为优先

**Comment by leeqvip** [comment]
@lg970044 See [v1.6.0](https://github.com/php-casbin/think-authz/releases/tag/v1.6.0).
