### ISSUE TITLE
Class 'tauthz\middleware\Enforcer' not found

### ISSUE THREAD

**Issue by daniuwo** [php-casbin/think-authz#7]
使用中间件 出现一个错误
![](https://ftp.bmp.ovh/imgs/2019/11/9b1d9f18b4eeeb74.png)

config/middleware.php
`<?php
// 中间件配置
return [
    // 别名或分组
    'alias'    => [
        'authz'  => tauthz\middleware\Basic::class,
    ],
    // 优先级设置，此数组中的中间件会按照数组中的顺序优先执行
    'priority' => [],
];
`

**Comment by leeqvip** [comment]
这是个bug。

**Comment by daniuwo** [comment]
> 这是个bug。

有空修复吗

**Comment by leeqvip** [comment]
已修复，版本`v1.0.1`。
